
services:
  postgres:
    container_name: postgres_payments
    image: "postgres:latest"
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: j@vacefer2005
    ports:
      - "2003:5432"
    volumes:
      - payments-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container-payment
    ports:
      - "6390:6379"

volumes:
  payments-db:
